baseurl = "/"
enableEmoji = true
footnotereturnlinkcontents = "â†©"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "Classic"

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 1
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2
[[menu.feed]]
name = "Subscribe"
url = "/index.xml"

[params]
custom_css = ["css/theme-override.css"]
description = "A simple, minimal blog for those who love text."
footer = "Open-Source | [Github](https://github.com/goodroot/hugo-classic) | [Keybase](https://keybase.io/goodroot)"
